"""rename contactPerson to contact_person

Revision ID: 473febddebf5
Revises: 
Create Date: 2025-04-15 19:58:53.776374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473febddebf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column(
            'contactPerson',
            existing_type=sa.String(length=255),
            new_column_name='contact_person',
            existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column(
            'contact_person',
            existing_type=sa.String(length=255),
            new_column_name='contactPerson',
            existing_nullable=False)

    # ### end Alembic commands ###
