"""add review fields to item_transaction

Revision ID: 6829e7012caa
Revises: 
Create Date: 2025-04-30 10:58:05.799415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6829e7012caa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testimonial', sa.String(length=1000), nullable=True, comment='Product review text from the buyer'))
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True, comment='Timestamp when review was submitted'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_transactions', schema=None) as batch_op:
        batch_op.drop_column('review_date')
        batch_op.drop_column('testimonial')

    # ### end Alembic commands ###
