"""add: original price column on item transaction

Revision ID: 73af3fb540e4
Revises: 
Create Date: 2025-04-18 06:35:19.435568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73af3fb540e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Numeric(
            precision=10, scale=2), nullable=True))

    op.execute("""
        UPDATE item_transactions
        SET original_price = total_price
        WHERE original_price IS NULL
    """)

    with op.batch_alter_table('item_transactions', schema=None) as batch_op:
        batch_op.alter_column('original_price',
                              existing_type=sa.Numeric(precision=10, scale=2),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_transactions', schema=None) as batch_op:
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
